"""Hugging Face packaging helpers (spec.md, "Publishing").

Two jobs the publish command delegates here: turning our raw SentencePiece
model into a ``MarianTokenizer`` that loads with ``from_pretrained``, and
rendering the model card. Keeping these pure and file-based makes them testable
without touching the Hub.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pandas as pd


def package_tokenizer(spm_path: Path, out_dir: Path) -> Path:
    """Write MarianTokenizer files (vocab.json, source/target.spm, config).

    The same SentencePiece model serves both sides. Language tags stay atomic
    because they were trained as user-defined symbols, so they already exist as
    single vocab entries.
    """
    import sentencepiece as spm
    from transformers import MarianTokenizer

    out_dir.mkdir(parents=True, exist_ok=True)
    sp = spm.SentencePieceProcessor()
    sp.load(str(spm_path))
    vocab = {sp.id_to_piece(i): i for i in range(sp.get_piece_size())}
    (out_dir / "vocab.json").write_text(
        json.dumps(vocab, ensure_ascii=False), encoding="utf-8"
    )
    shutil.copy(spm_path, out_dir / "source.spm")
    shutil.copy(spm_path, out_dir / "target.spm")
    tok = MarianTokenizer(
        vocab=str(out_dir / "vocab.json"),
        source_spm=str(out_dir / "source.spm"),
        target_spm=str(out_dir / "target.spm"),
        source_lang="grc",
        target_lang="mul",
        unk_token="<unk>",
        eos_token="</s>",
        pad_token="<pad>",
    )
    tok.save_pretrained(str(out_dir))
    return out_dir


def _yaml_metadata(languages, licence, tags) -> str:
    lang_lines = "\n".join(f"  - {c}" for c in sorted(set(languages)))
    tag_lines = "\n".join(f"  - {t}" for t in tags)
    return (
        "---\n"
        "library_name: transformers\n"
        "pipeline_tag: translation\n"
        f"license: {licence}\n"
        "language:\n"
        f"{lang_lines}\n"
        "tags:\n"
        f"{tag_lines}\n"
        "---\n"
    )


def build_model_card(
    *,
    repo_id: str,
    experiment: str,
    n_params: int,
    licences: pd.DataFrame,
    holdouts: dict,
    metrics: pd.DataFrame,
    model_licence: str,
    git_commit: str,
    seed: int,
) -> str:
    """Render the model card (README.md) for a published run."""
    languages = sorted(set(licences["languageCode"]))
    tags = ["translation", "bible", "marian", "multilingual", "from-scratch"]
    header = _yaml_metadata(languages, model_licence, tags)

    holdout_lines = "\n".join(
        f"| `{t}` | {', '.join(b)} |" for t, b in holdouts.items()
    )
    src_table = licences.rename(
        columns={"translationId": "translation", "languageCode": "language"}
    )[["translation", "language", "licence"]].to_markdown(index=False)
    metric_table = (
        metrics.to_markdown(index=False) if metrics is not None and len(metrics)
        else "Metrics were not recorded for this run."
    )

    body = f"""# {repo_id.split('/')[-1]}

A multilingual, from scratch encoder decoder transformer that translates verses
of the Bible from a fixed Koine Greek source into many languages. It reproduces
and extends the closed text translation experiment first carried out by Sami
Liedes in 2018, replacing his convolutional sequence to sequence model with a
modern transformer and adding quantitative evaluation. This checkpoint comes
from the `{experiment}` experiment.

The model is trained on verse aligned Bible translations from the eBible corpus.
Whole books are withheld from certain languages during training, and the model
then generates those withheld books. The practical aim is to draft scripture in
a language for which parts of the Bible do not yet exist, using the many
translations the model has already seen as context.

## How to use

```python
from transformers import MarianMTModel, MarianTokenizer

model = MarianMTModel.from_pretrained("{repo_id}")
tokenizer = MarianTokenizer.from_pretrained("{repo_id}")

# Prepend the target language tag (for example <2spa> for Spanish) to the
# Koine Greek source verse.
source = "<2spa> Ἐν ἀρχῇ ἐποίησεν ὁ Θεὸς τὸν οὐρανὸν καὶ τὴν γῆν"
batch = tokenizer([source], return_tensors="pt")
generated = model.generate(**batch, num_beams=5, max_length=192)
print(tokenizer.decode(generated[0], skip_special_tokens=True))
```

## Model details

- Architecture: MarianMT style encoder decoder, randomly initialised (no
  pretrained weights).
- Parameters: approximately {n_params / 1e6:.0f} million.
- Source language: composite Koine Greek (Brenton Septuagint for the Old
  Testament, Tischendorf for the New Testament), in Greek script.
- Target languages: indicated by an atomic `<2xxx>` tag prepended to the
  source verse.
- Tokeniser: SentencePiece, trained on the training split only.

## Held out books

The following books were withheld from training and generated by the model.

| Translation | Held out |
|---|---|
{holdout_lines}

## Evaluation

Scores are corpus level per held out book, following the silnlp and sacreBLEU
conventions. chrF3 is the headline metric. The source copy baseline is the
score obtained by returning the Greek source verse unchanged.

{metric_table}

## Training data and licensing

This model was trained only on translations whose licences permit derivative
works, so that the model may itself be shared. The published model is released
under `{model_licence}`. Every source translation and its licence is listed
below.

{src_table}

## Reproducibility

- Experiment: `{experiment}`
- Git commit: `{git_commit}`
- Random seed: `{seed}`

The full training and evaluation code, configuration and selection list are in
the project repository.

## Acknowledgement

This work reproduces the closed text Bible translation experiment described by
Sami Liedes in his 2018 blog post "Machine translating the Bible into new
languages". The reproduction and this model are independent work and are not
endorsed by him.
"""
    return header + "\n" + body
