"""Fine-tune NLLB-200 on the closed text, many-to-many (spec.md phase 7).

    uv run python -m samileides.train_nllb --config configs/experiments/nllb_ie.yaml

A separate entry point from `samileides.train` because NLLB brings its own
tokeniser and FLORES-200 language tokens. This is the "pretrained comparison"
track: the model already knows the target languages, so it is reported
separately from the from-scratch results. Held-out books are generated by
translating from a fixed pivot language (NLLB has no Koine Greek), so the task
is easier than the from-scratch Greek-source generation; that difference is
noted in the results.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd
import torch

from .canon import book_of
from .config import ExperimentConfig
from .data import VREF_COLUMN, repo_root
from .data_pipeline import prepare
from .dataset import Collator
from .evaluate import best_reference_baseline, score
from .generate import other_language_candidates
from .nllb import NllbDataset, build_nllb_pairs, load_flores_map
from .preprocess import normalise
from .splits import assert_no_leakage


def _pivot_translation(cfg, data) -> str:
    """The translationId used as the source language for held-out generation."""
    for tid, code in data.language_of.items():
        if code == cfg.data.pivot:
            return tid
    raise SystemExit(f"pivot language {cfg.data.pivot!r} not in the selection")


@torch.no_grad()
def nllb_generate(model, tok, texts, src_code, tgt_code, beam, max_length, batch_size, device):
    tok.src_lang = src_code
    forced_bos = tok.convert_tokens_to_ids(tgt_code)
    hyps = []
    for i in range(0, len(texts), batch_size):
        batch = tok(texts[i:i + batch_size], return_tensors="pt",
                    padding=True, truncation=True, max_length=max_length).to(device)
        out = model.generate(**batch, forced_bos_token_id=forced_bos,
                             num_beams=beam, max_length=max_length)
        hyps.extend(tok.batch_decode(out, skip_special_tokens=True))
    return hyps


def generate_and_score(cfg, data, model, tok, output: Path, device, beam, batch_size):
    flores = load_flores_map()
    pivot_tid = _pivot_translation(cfg, data)
    out_dir = output / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    rows = []
    for translation, _ in data.holdouts.items():
        tgt_code = flores.get(data.language_of.get(translation))
        if tgt_code is None:
            continue
        sub = data.test_pairs[data.test_pairs["translation"] == translation]
        for book in sorted(sub[VREF_COLUMN].map(book_of).unique()):
            vrefs = [v for v in sub[sub[VREF_COLUMN].map(book_of) == book][VREF_COLUMN]
                     if data.verses.at[v, pivot_tid]]
            if not vrefs:
                continue
            srcs = [normalise(data.verses.at[v, pivot_tid]) for v in vrefs]
            refs = [normalise(data.verses.at[v, translation]) for v in vrefs]
            hyps = nllb_generate(model, tok, srcs, flores[cfg.data.pivot], tgt_code,
                                 beam, cfg.inference.max_length, batch_size, device)
            (out_dir / f"{translation}-{book}.txt").write_text(
                "\n".join(f"{v}\t{h}" for v, h in zip(vrefs, hyps)) + "\n", encoding="utf-8")
            metrics = score(hyps, refs)
            cands = other_language_candidates(vrefs, data.verses, translation, data.language_of)
            other_lang, other_chrf = best_reference_baseline(refs, cands)
            rows.append({"translation": translation, "language": data.language_of[translation],
                         "book": book, "verses": len(vrefs),
                         "pivot": cfg.data.pivot, **metrics,
                         "other_chrF3": other_chrf, "other_lang": other_lang})
            print(f"  {translation}/{book}: chrF3={metrics['chrF3']} "
                  f"(pivot={cfg.data.pivot}->; other={other_chrf} [{other_lang}])")
    table = pd.DataFrame(rows)
    if len(table):
        table.to_csv(out_dir / "metrics.csv", index=False)
        (out_dir / "metrics.md").write_text(table.to_markdown(index=False), encoding="utf-8")
    return table


def run(args) -> None:
    from transformers import (AutoModelForSeq2SeqLM, AutoTokenizer,
                              EarlyStoppingCallback, Seq2SeqTrainer,
                              Seq2SeqTrainingArguments)

    cfg = ExperimentConfig.load(args.config)
    output = Path(args.output_dir) if args.output_dir else repo_root() / "checkpoints" / cfg.name
    output.mkdir(parents=True, exist_ok=True)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    data = prepare(cfg)
    assert_no_leakage(data.splits, data.holdouts)
    flores = load_flores_map()

    train_pairs = build_nllb_pairs(data.splits.train, data.splits.valid, data.verses,
                                   data.language_of, flores, k=cfg.data.k, seed=cfg.training.seed)
    valid_pairs = build_nllb_pairs(data.splits.valid, data.splits.valid, data.verses,
                                   data.language_of, flores, k=1, seed=cfg.training.seed)
    print(f"NLLB fine-tune '{cfg.name}': train pairs={len(train_pairs)} valid={len(valid_pairs)}")

    tok = AutoTokenizer.from_pretrained(cfg.model.pretrained)
    model = AutoModelForSeq2SeqLM.from_pretrained(cfg.model.pretrained, dtype=torch.bfloat16)
    if cfg.training.gradient_checkpointing:
        model.config.use_cache = False
        model.gradient_checkpointing_enable()

    train_ds = NllbDataset(train_pairs, tok, cfg.data.max_len)
    valid_ds = NllbDataset(valid_pairs, tok, cfg.data.max_len)
    collator = Collator(pad_id=tok.pad_token_id, decoder_start_id=tok.eos_token_id)

    max_steps = args.max_steps or cfg.training.max_steps
    eval_steps = min(cfg.training.eval_every_steps, max_steps)
    targs = Seq2SeqTrainingArguments(
        output_dir=str(output), max_steps=max_steps,
        per_device_train_batch_size=cfg.training.per_device_batch_size or 8,
        per_device_eval_batch_size=cfg.training.per_device_batch_size or 8,
        gradient_accumulation_steps=cfg.training.gradient_accumulation,
        learning_rate=cfg.training.lr, warmup_steps=cfg.training.warmup_steps,
        lr_scheduler_type=cfg.training.lr_scheduler, max_grad_norm=cfg.training.max_grad_norm,
        label_smoothing_factor=cfg.model.label_smoothing, bf16=True,
        eval_strategy="steps", eval_steps=eval_steps, save_strategy="steps",
        save_steps=eval_steps, save_total_limit=1, load_best_model_at_end=True,
        metric_for_best_model="eval_loss", greater_is_better=False,
        logging_steps=max(1, min(50, max_steps // 10)), seed=cfg.training.seed,
        report_to=[], remove_unused_columns=False, dataloader_num_workers=args.num_workers,
    )
    trainer = Seq2SeqTrainer(model=model, args=targs, train_dataset=train_ds,
                            eval_dataset=valid_ds, data_collator=collator,
                            callbacks=[EarlyStoppingCallback(cfg.training.early_stopping_patience)])
    trainer.train()
    metrics = trainer.evaluate()
    print(f"  final eval: {metrics}")
    trainer.save_model(str(output))
    tok.save_pretrained(str(output))
    import shutil
    shutil.copy(cfg.path, output / "config.yaml")

    if args.generate_after:
        print("Generating held-out books from the pivot ...")
        model = model.to(device).eval()
        generate_and_score(cfg, data, model, tok, output, device,
                           beam=cfg.inference.beam, batch_size=args.gen_batch_size)
    (output / "train_summary.json").write_text(
        json.dumps({"name": cfg.name, "eval_loss": metrics.get("eval_loss"),
                    "pretrained": cfg.model.pretrained, "train_pairs": len(train_pairs)}, indent=2),
        encoding="utf-8")
    print(f"Saved to {output}")


def main() -> None:
    p = argparse.ArgumentParser(description="Fine-tune NLLB on the closed text")
    p.add_argument("--config", required=True)
    p.add_argument("--output-dir", default=None)
    p.add_argument("--max-steps", type=int, default=None)
    p.add_argument("--num-workers", type=int, default=2)
    p.add_argument("--generate-after", action="store_true")
    p.add_argument("--gen-batch-size", type=int, default=16)
    run(p.parse_args())


if __name__ == "__main__":
    main()
